// Copyright 2026 Team Beaver. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"

namespace  WPPortalLightTags
{
	/** Excludes this Light from Portal Light collection and transmission. */
	inline const FName Disabled(TEXT("WP.PortalLight.Disabled"));
	
	/** Identifies a proxy Light generated by the Portal system. */
	inline const FName Generated(TEXT("WP.PortalLight.Generated"));
}
