#!/usr/bin/env python3
"""Generate the project-owned Portal-inspired laser gimmick source meshes.

The generator intentionally uses only the Python standard library so the source
art can be reproduced on any machine without Blender or third-party packages.
All dimensions are authored in Unreal centimetres and local +X is the forward
axis used by the laser gameplay classes.
"""

from __future__ import annotations

import argparse
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


@dataclass(frozen=True)
class Vec3:
    x: float
    y: float
    z: float

    def __add__(self, other: "Vec3") -> "Vec3":
        return Vec3(self.x + other.x, self.y + other.y, self.z + other.z)

    def __sub__(self, other: "Vec3") -> "Vec3":
        return Vec3(self.x - other.x, self.y - other.y, self.z - other.z)

    def __mul__(self, scalar: float) -> "Vec3":
        return Vec3(self.x * scalar, self.y * scalar, self.z * scalar)

    def dot(self, other: "Vec3") -> float:
        return self.x * other.x + self.y * other.y + self.z * other.z

    def cross(self, other: "Vec3") -> "Vec3":
        return Vec3(
            self.y * other.z - self.z * other.y,
            self.z * other.x - self.x * other.z,
            self.x * other.y - self.y * other.x,
        )

    def normalized(self) -> "Vec3":
        length = math.sqrt(self.dot(self))
        if length <= 1.0e-8:
            raise ValueError("Cannot normalize a zero-length vector")
        return self * (1.0 / length)


@dataclass(frozen=True)
class Face:
    indices: tuple[int, int, int]
    material: str
    group: str
    smooth: bool


class Mesh:
    def __init__(self, name: str) -> None:
        self.name = name
        self.vertices: list[Vec3] = []
        self.faces: list[Face] = []

    def vertex(self, value: Vec3) -> int:
        self.vertices.append(value)
        return len(self.vertices)

    def triangle(
        self,
        a: int,
        b: int,
        c: int,
        material: str,
        group: str,
        smooth: bool = False,
    ) -> None:
        self.faces.append(Face((a, b, c), material, group, smooth))

    def quad(
        self,
        a: int,
        b: int,
        c: int,
        d: int,
        material: str,
        group: str,
        smooth: bool = False,
    ) -> None:
        self.triangle(a, b, c, material, group, smooth)
        self.triangle(a, c, d, material, group, smooth)

    def write(self, output_path: Path) -> None:
        lines = [
            "# Generated by Scripts/LaserGimmicks/generate_laser_gimmick_meshes.py",
            f"mtllib {output_path.stem}.mtl",
            f"o {self.name}",
            f"g {self.name}",
        ]
        lines.extend(f"v {v.x:.6f} {v.y:.6f} {v.z:.6f}" for v in self.vertices)
        # UE 5.8's Interchange OBJ translator expects valid, non-degenerate UVs
        # when it builds tangents. Per-triangle UV islands are sufficient for
        # the solid-color materials and keep every triangle well-defined.
        for _face in self.faces:
            lines.extend(("vt 0.000000 0.000000", "vt 1.000000 0.000000", "vt 0.000000 1.000000"))

        current_material: str | None = None
        for face_index, face in enumerate(self.faces):
            # Keep one OBJ group so Interchange imports one StaticMesh asset.
            # Material changes alone create the three named material slots.
            if face.material != current_material:
                lines.append(f"usemtl {face.material}")
                current_material = face.material
            first_uv_index = face_index * 3 + 1
            lines.append(
                "f "
                + " ".join(
                    f"{vertex_index}/{first_uv_index + corner_index}"
                    for corner_index, vertex_index in enumerate(face.indices)
                )
            )

        output_path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
        write_mtl(output_path.with_suffix(".mtl"))


def rotate_xyz(value: Vec3, rotation_degrees: Vec3) -> Vec3:
    rx, ry, rz = (math.radians(v) for v in (rotation_degrees.x, rotation_degrees.y, rotation_degrees.z))
    cx, sx = math.cos(rx), math.sin(rx)
    cy, sy = math.cos(ry), math.sin(ry)
    cz, sz = math.cos(rz), math.sin(rz)

    x1, y1, z1 = value.x, value.y * cx - value.z * sx, value.y * sx + value.z * cx
    x2, y2, z2 = x1 * cy + z1 * sy, y1, -x1 * sy + z1 * cy
    return Vec3(x2 * cz - y2 * sz, x2 * sz + y2 * cz, z2)


def add_box(
    mesh: Mesh,
    center: Vec3,
    size: Vec3,
    material: str,
    group: str,
    rotation: Vec3 = Vec3(0.0, 0.0, 0.0),
) -> None:
    hx, hy, hz = size.x * 0.5, size.y * 0.5, size.z * 0.5
    local = (
        Vec3(-hx, -hy, -hz), Vec3(hx, -hy, -hz), Vec3(hx, hy, -hz), Vec3(-hx, hy, -hz),
        Vec3(-hx, -hy, hz), Vec3(hx, -hy, hz), Vec3(hx, hy, hz), Vec3(-hx, hy, hz),
    )
    v = [mesh.vertex(rotate_xyz(point, rotation) + center) for point in local]
    for a, b, c, d in (
        (0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4),
        (3, 7, 6, 2), (0, 4, 7, 3), (1, 2, 6, 5),
    ):
        mesh.quad(v[a], v[b], v[c], v[d], material, group)


def perpendicular_basis(axis: Vec3) -> tuple[Vec3, Vec3]:
    direction = axis.normalized()
    reference = Vec3(0.0, 0.0, 1.0) if abs(direction.z) < 0.9 else Vec3(0.0, 1.0, 0.0)
    side = reference.cross(direction).normalized()
    up = direction.cross(side).normalized()
    return side, up


def add_cylinder(
    mesh: Mesh,
    start: Vec3,
    end: Vec3,
    radius_start: float,
    material: str,
    group: str,
    segments: int = 32,
    radius_end: float | None = None,
) -> None:
    radius_end = radius_start if radius_end is None else radius_end
    side, up = perpendicular_basis(end - start)
    first_ring: list[int] = []
    second_ring: list[int] = []
    for index in range(segments):
        angle = math.tau * index / segments
        radial = side * math.cos(angle) + up * math.sin(angle)
        first_ring.append(mesh.vertex(start + radial * radius_start))
        second_ring.append(mesh.vertex(end + radial * radius_end))

    for index in range(segments):
        next_index = (index + 1) % segments
        mesh.quad(
            first_ring[index], first_ring[next_index], second_ring[next_index], second_ring[index],
            material, group, smooth=True,
        )

    start_center = mesh.vertex(start)
    end_center = mesh.vertex(end)
    for index in range(segments):
        next_index = (index + 1) % segments
        mesh.triangle(start_center, first_ring[next_index], first_ring[index], material, group)
        mesh.triangle(end_center, second_ring[index], second_ring[next_index], material, group)


def add_torus_x(
    mesh: Mesh,
    center: Vec3,
    major_radius: float,
    minor_radius: float,
    material: str,
    group: str,
    major_segments: int = 32,
    minor_segments: int = 8,
) -> None:
    rings: list[list[int]] = []
    for major_index in range(major_segments):
        theta = math.tau * major_index / major_segments
        ring: list[int] = []
        for minor_index in range(minor_segments):
            phi = math.tau * minor_index / minor_segments
            radial_distance = major_radius + minor_radius * math.cos(phi)
            ring.append(
                mesh.vertex(
                    Vec3(
                        center.x + minor_radius * math.sin(phi),
                        center.y + radial_distance * math.cos(theta),
                        center.z + radial_distance * math.sin(theta),
                    )
                )
            )
        rings.append(ring)

    for major_index in range(major_segments):
        next_major = (major_index + 1) % major_segments
        for minor_index in range(minor_segments):
            next_minor = (minor_index + 1) % minor_segments
            mesh.quad(
                rings[major_index][minor_index],
                rings[next_major][minor_index],
                rings[next_major][next_minor],
                rings[major_index][next_minor],
                material,
                group,
                smooth=True,
            )


def add_ellipsoid(
    mesh: Mesh,
    center: Vec3,
    radius: Vec3,
    material: str,
    group: str,
    longitude_segments: int = 24,
    latitude_segments: int = 12,
) -> None:
    rings: list[list[int]] = []
    for latitude_index in range(1, latitude_segments):
        latitude = -math.pi * 0.5 + math.pi * latitude_index / latitude_segments
        ring: list[int] = []
        for longitude_index in range(longitude_segments):
            longitude = math.tau * longitude_index / longitude_segments
            ring.append(
                mesh.vertex(
                    Vec3(
                        center.x + radius.x * math.sin(latitude),
                        center.y + radius.y * math.cos(latitude) * math.cos(longitude),
                        center.z + radius.z * math.cos(latitude) * math.sin(longitude),
                    )
                )
            )
        rings.append(ring)

    negative_pole = mesh.vertex(Vec3(center.x - radius.x, center.y, center.z))
    positive_pole = mesh.vertex(Vec3(center.x + radius.x, center.y, center.z))
    for longitude_index in range(longitude_segments):
        next_longitude = (longitude_index + 1) % longitude_segments
        mesh.triangle(negative_pole, rings[0][next_longitude], rings[0][longitude_index], material, group, True)
        mesh.triangle(rings[-1][longitude_index], rings[-1][next_longitude], positive_pole, material, group, True)
    for latitude_index in range(len(rings) - 1):
        for longitude_index in range(longitude_segments):
            next_longitude = (longitude_index + 1) % longitude_segments
            mesh.quad(
                rings[latitude_index][longitude_index],
                rings[latitude_index][next_longitude],
                rings[latitude_index + 1][next_longitude],
                rings[latitude_index + 1][longitude_index],
                material,
                group,
                smooth=True,
            )


def add_radial_boxes(
    mesh: Mesh,
    count: int,
    center: Vec3,
    radial_distance: float,
    size: Vec3,
    material: str,
    group: str,
    angular_offset_degrees: float = 0.0,
) -> None:
    for index in range(count):
        angle_degrees = angular_offset_degrees + 360.0 * index / count
        angle = math.radians(angle_degrees)
        location = center + Vec3(0.0, radial_distance * math.cos(angle), radial_distance * math.sin(angle))
        add_box(mesh, location, size, material, f"{group}_{index:02d}", Vec3(angle_degrees, 0.0, 0.0))


def build_emitter() -> Mesh:
    mesh = Mesh("SM_LaserEmitter")
    add_cylinder(mesh, Vec3(0.0, 0.0, 0.0), Vec3(9.0, 0.0, 0.0), 55.0, "Mechanism", "RearMount", 40)
    add_torus_x(mesh, Vec3(8.0, 0.0, 0.0), 46.0, 5.0, "Mechanism", "RearMountRing", 40, 8)
    add_cylinder(mesh, Vec3(8.0, 0.0, 0.0), Vec3(38.0, 0.0, 0.0), 39.0, "Mechanism", "AxialHousing", 40, 30.0)
    add_cylinder(mesh, Vec3(34.0, 0.0, 0.0), Vec3(69.0, 0.0, 0.0), 24.0, "Mechanism", "EmitterBarrel", 32, 20.0)
    add_torus_x(mesh, Vec3(42.0, 0.0, 0.0), 27.0, 3.2, "Mechanism", "BarrelRing", 32, 8)

    add_radial_boxes(mesh, 3, Vec3(34.0, 0.0, 0.0), 43.0, Vec3(48.0, 34.0, 15.0), "Shell", "ShellFin", 90.0)
    add_radial_boxes(mesh, 3, Vec3(16.0, 0.0, 0.0), 47.0, Vec3(20.0, 27.0, 12.0), "Shell", "MountClamp", 90.0)

    add_cylinder(mesh, Vec3(66.0, 0.0, 0.0), Vec3(73.0, 0.0, 0.0), 21.0, "Mechanism", "OpticHousing", 32, 18.0)
    add_cylinder(mesh, Vec3(72.5, 0.0, 0.0), Vec3(75.0, 0.0, 0.0), 16.5, "Optic", "EmitterOptic", 32, 15.0)
    add_ellipsoid(mesh, Vec3(74.0, 0.0, 0.0), Vec3(2.0, 14.5, 14.5), "Optic", "EmitterLens", 32, 10)
    return mesh


def build_receiver() -> Mesh:
    mesh = Mesh("SM_LaserReceiver")
    add_cylinder(mesh, Vec3(-13.0, 0.0, 0.0), Vec3(-5.0, 0.0, 0.0), 94.0, "Mechanism", "ReceiverBackplate", 48, 90.0)
    add_cylinder(mesh, Vec3(-5.0, 0.0, 0.0), Vec3(5.0, 0.0, 0.0), 78.0, "Mechanism", "ReceiverRecess", 48, 68.0)
    add_torus_x(mesh, Vec3(1.0, 0.0, 0.0), 70.0, 4.5, "Mechanism", "OuterTargetRing", 48, 8)
    add_torus_x(mesh, Vec3(5.0, 0.0, 0.0), 47.0, 4.0, "Mechanism", "InnerTargetRing", 40, 8)

    add_radial_boxes(mesh, 3, Vec3(-1.0, 0.0, 0.0), 75.0, Vec3(15.0, 44.0, 20.0), "Shell", "ReceiverClamp", 90.0)
    add_radial_boxes(mesh, 3, Vec3(6.0, 0.0, 0.0), 57.0, Vec3(12.0, 28.0, 13.0), "Shell", "ReceiverPetal", 90.0)

    add_cylinder(mesh, Vec3(3.0, 0.0, 0.0), Vec3(12.0, 0.0, 0.0), 34.0, "Mechanism", "ReceiverCoreHousing", 40, 29.0)
    add_cylinder(mesh, Vec3(11.5, 0.0, 0.0), Vec3(15.0, 0.0, 0.0), 26.0, "Optic", "ReceiverOptic", 40, 23.0)
    add_ellipsoid(mesh, Vec3(14.0, 0.0, 0.0), Vec3(2.5, 22.0, 22.0), "Optic", "ReceiverLens", 32, 10)
    return mesh


def face_basis(normal: Vec3) -> tuple[Vec3, Vec3]:
    return perpendicular_basis(normal)


def add_cube_face_details(mesh: Mesh, normal: Vec3, face_index: int) -> None:
    side, up = face_basis(normal)
    face_center = normal * 47.0
    for side_sign in (-1.0, 1.0):
        for up_sign in (-1.0, 1.0):
            plate_center = face_center + side * (30.0 * side_sign) + up * (30.0 * up_sign)
            # Thin white corner tiles sit on each face while the hidden physics cube remains 100 cm.
            if abs(normal.x) > 0.5:
                size = Vec3(5.0, 25.0, 25.0)
            elif abs(normal.y) > 0.5:
                size = Vec3(25.0, 5.0, 25.0)
            else:
                size = Vec3(25.0, 25.0, 5.0)
            add_box(mesh, plate_center, size, "Shell", f"Face{face_index}_CornerShell")

    housing_start = normal * 44.0
    housing_end = normal * 53.0
    optic_start = normal * 52.0
    optic_end = normal * 55.0
    add_cylinder(mesh, housing_start, housing_end, 23.0, "Mechanism", f"Face{face_index}_LensHousing", 32, 20.0)
    add_cylinder(mesh, optic_start, optic_end, 15.5, "Optic", f"Face{face_index}_Optic", 32, 14.5)


def build_redirector() -> Mesh:
    mesh = Mesh("SM_LaserRedirectorCube")
    add_box(mesh, Vec3(0.0, 0.0, 0.0), Vec3(84.0, 84.0, 84.0), "Mechanism", "DarkCore")

    for y in (-44.0, 44.0):
        for z in (-44.0, 44.0):
            add_box(mesh, Vec3(0.0, y, z), Vec3(92.0, 7.0, 7.0), "Mechanism", "FrameX")
    for x in (-44.0, 44.0):
        for z in (-44.0, 44.0):
            add_box(mesh, Vec3(x, 0.0, z), Vec3(7.0, 92.0, 7.0), "Mechanism", "FrameY")
    for x in (-44.0, 44.0):
        for y in (-44.0, 44.0):
            add_box(mesh, Vec3(x, y, 0.0), Vec3(7.0, 7.0, 92.0), "Mechanism", "FrameZ")

    normals = (
        Vec3(1.0, 0.0, 0.0), Vec3(-1.0, 0.0, 0.0),
        Vec3(0.0, 1.0, 0.0), Vec3(0.0, -1.0, 0.0),
        Vec3(0.0, 0.0, 1.0), Vec3(0.0, 0.0, -1.0),
    )
    for face_index, normal in enumerate(normals):
        add_cube_face_details(mesh, normal, face_index)

    add_torus_x(mesh, Vec3(54.0, 0.0, 0.0), 17.5, 2.0, "Optic", "OutputDirectionRing", 32, 8)
    return mesh


def write_mtl(path: Path) -> None:
    contents = """# Preview materials; Unreal assigns project PBR materials to these named slots.
newmtl Shell
Ka 0.080000 0.080000 0.080000
Kd 0.820000 0.840000 0.820000
Ks 0.250000 0.250000 0.250000
Ns 96.000000
illum 2

newmtl Mechanism
Ka 0.010000 0.012000 0.015000
Kd 0.025000 0.032000 0.040000
Ks 0.500000 0.520000 0.550000
Ns 180.000000
illum 2

newmtl Optic
Ka 0.100000 0.002000 0.001000
Kd 0.650000 0.008000 0.003000
Ks 0.900000 0.250000 0.200000
Ke 1.000000 0.010000 0.002000
Ns 220.000000
illum 2
"""
    path.write_text(contents, encoding="utf-8", newline="\n")


def generate(output_directory: Path) -> Iterable[Path]:
    output_directory.mkdir(parents=True, exist_ok=True)
    outputs: list[Path] = []
    for mesh in (build_emitter(), build_receiver(), build_redirector()):
        output_path = output_directory / f"{mesh.name}.obj"
        mesh.write(output_path)
        outputs.extend((output_path, output_path.with_suffix(".mtl")))
    return outputs


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[2] / "SourceArt" / "LaserGimmicks",
        help="Directory that receives the generated OBJ and MTL files.",
    )
    arguments = parser.parse_args()
    for generated_path in generate(arguments.output.resolve()):
        print(generated_path)


if __name__ == "__main__":
    main()
