#!/usr/bin/env python3
"""Generate Portal-inspired Energy Ball device source meshes.

Only the Python standard library and the project's deterministic laser mesh
helpers are used. Dimensions are authored in Unreal centimetres and local +X
is the firing/receiving outward axis.
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path
from typing import Iterable


def load_mesh_tools():
    helper_path = (
        Path(__file__).resolve().parents[1]
        / "LaserGimmicks"
        / "generate_laser_gimmick_meshes.py"
    )
    specification = importlib.util.spec_from_file_location("laser_gimmick_mesh_tools", helper_path)
    if specification is None or specification.loader is None:
        raise RuntimeError(f"Could not load deterministic mesh helpers: {helper_path}")
    module = importlib.util.module_from_spec(specification)
    sys.modules[specification.name] = module
    specification.loader.exec_module(module)
    return module


TOOLS = load_mesh_tools()
Mesh = TOOLS.Mesh
Vec3 = TOOLS.Vec3
add_box = TOOLS.add_box
add_cylinder = TOOLS.add_cylinder
add_ellipsoid = TOOLS.add_ellipsoid
add_radial_boxes = TOOLS.add_radial_boxes
add_torus_x = TOOLS.add_torus_x


def build_emitter() -> Mesh:
    mesh = Mesh("SM_EnergyBallEmitter")

    # Broad wall flange and dark pressure chamber.
    add_cylinder(mesh, Vec3(-8.0, 0.0, 0.0), Vec3(2.0, 0.0, 0.0), 57.0, "Shell", "RearShell", 48)
    add_torus_x(mesh, Vec3(1.0, 0.0, 0.0), 49.0, 5.0, "Mechanism", "RearSeal", 48, 8)
    add_ellipsoid(mesh, Vec3(24.0, 0.0, 0.0), Vec3(30.0, 51.0, 51.0), "Mechanism", "PressureChamber", 40, 18)

    # Six white focusing clamps give the launcher its Portal-1-inspired silhouette.
    add_radial_boxes(
        mesh, 6, Vec3(26.0, 0.0, 0.0), 48.0, Vec3(48.0, 15.0, 19.0),
        "Shell", "OuterClamp", 30.0,
    )
    add_radial_boxes(
        mesh, 6, Vec3(49.0, 0.0, 0.0), 35.0, Vec3(24.0, 12.0, 15.0),
        "Shell", "ClampTip", 30.0,
    )
    add_radial_boxes(
        mesh, 6, Vec3(31.0, 0.0, 0.0), 34.0, Vec3(38.0, 6.0, 8.0),
        "Mechanism", "ClampRail", 30.0,
    )

    # Concentric barrel hardware narrows toward the exact X=70 cm muzzle.
    add_cylinder(mesh, Vec3(28.0, 0.0, 0.0), Vec3(52.0, 0.0, 0.0), 38.0, "Mechanism", "OuterBarrel", 40, 31.0)
    add_torus_x(mesh, Vec3(47.0, 0.0, 0.0), 31.0, 3.5, "Shell", "BarrelCollar", 40, 8)
    add_cylinder(mesh, Vec3(49.0, 0.0, 0.0), Vec3(64.0, 0.0, 0.0), 27.0, "Mechanism", "InnerBarrel", 40, 22.0)
    add_torus_x(mesh, Vec3(63.0, 0.0, 0.0), 23.0, 3.0, "Optic", "FocusingRing", 40, 8)
    add_cylinder(mesh, Vec3(62.0, 0.0, 0.0), Vec3(68.0, 0.0, 0.0), 18.0, "Optic", "EmitterLens", 40, 15.0)
    add_ellipsoid(mesh, Vec3(67.0, 0.0, 0.0), Vec3(3.0, 13.0, 13.0), "Optic", "EmitterCore", 32, 12)
    return mesh


def build_receiver() -> Mesh:
    mesh = Mesh("SM_EnergyBallReceiver")

    # A deep catcher keeps the existing 75 cm overlap volume visually aligned
    # with the intake without changing Energy Ball gameplay timing.
    add_cylinder(mesh, Vec3(-10.0, 0.0, 0.0), Vec3(1.0, 0.0, 0.0), 73.0, "Shell", "RearShell", 48)
    add_torus_x(mesh, Vec3(3.0, 0.0, 0.0), 64.0, 5.5, "Mechanism", "RearSeal", 48, 8)
    add_ellipsoid(mesh, Vec3(27.0, 0.0, 0.0), Vec3(34.0, 64.0, 64.0), "Mechanism", "CatcherBody", 40, 18)

    # Eight long shell claws surround the recessed capture chamber.
    add_radial_boxes(
        mesh, 8, Vec3(27.0, 0.0, 0.0), 61.0, Vec3(62.0, 14.0, 21.0),
        "Shell", "CaptureClaw", 22.5,
    )
    add_radial_boxes(
        mesh, 8, Vec3(55.0, 0.0, 0.0), 46.0, Vec3(24.0, 11.0, 16.0),
        "Shell", "ClawTip", 22.5,
    )
    add_radial_boxes(
        mesh, 8, Vec3(34.0, 0.0, 0.0), 46.0, Vec3(48.0, 5.0, 7.0),
        "Mechanism", "ClawRail", 22.5,
    )

    add_cylinder(mesh, Vec3(18.0, 0.0, 0.0), Vec3(52.0, 0.0, 0.0), 49.0, "Mechanism", "CaptureFunnel", 48, 31.0)
    add_torus_x(mesh, Vec3(49.0, 0.0, 0.0), 35.0, 4.0, "Shell", "FunnelCollar", 48, 8)
    add_torus_x(mesh, Vec3(59.0, 0.0, 0.0), 29.0, 4.0, "Optic", "CaptureRing", 40, 8)
    add_cylinder(mesh, Vec3(53.0, 0.0, 0.0), Vec3(65.0, 0.0, 0.0), 26.0, "Optic", "CaptureLens", 40, 20.0)
    add_ellipsoid(mesh, Vec3(67.0, 0.0, 0.0), Vec3(7.0, 19.0, 19.0), "Optic", "CaptureCore", 32, 14)
    return mesh


def generate(output_directory: Path) -> Iterable[Path]:
    output_directory.mkdir(parents=True, exist_ok=True)
    outputs: list[Path] = []
    for mesh in (build_emitter(), build_receiver()):
        output_path = output_directory / f"{mesh.name}.obj"
        mesh.write(output_path)
        # Correct the provenance line inherited from the shared writer.
        contents = output_path.read_text(encoding="utf-8")
        contents = contents.replace(
            "# Generated by Scripts/LaserGimmicks/generate_laser_gimmick_meshes.py",
            "# Generated by Scripts/EnergyBallGimmicks/generate_energy_ball_gimmick_meshes.py",
            1,
        )
        output_path.write_text(contents, encoding="utf-8", newline="\n")
        outputs.extend((output_path, output_path.with_suffix(".mtl")))
    return outputs


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[2] / "SourceArt" / "EnergyBallGimmicks",
        help="Directory that receives the generated OBJ and MTL files.",
    )
    arguments = parser.parse_args()
    for generated_path in generate(arguments.output.resolve()):
        print(generated_path)


if __name__ == "__main__":
    main()
